<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-25T15:56:26 IST" name="Grouping" finished-at="2024-08-25T15:56:29 IST" duration-ms="3252">
    <groups>
      <group name="Smoke testing">
        <method signature="LoginPage_Test.verify_User_is_Able_toLoginUsing_Invalid_UserName_and_Validpassword()[pri:0, instance:testScript.LoginPage_Test@c05fddc]" name="verify_User_is_Able_toLoginUsing_Invalid_UserName_and_Validpassword" class="testScript.LoginPage_Test"/>
      </group> <!-- Smoke testing -->
    </groups>
    <test started-at="2024-08-25T15:56:26 IST" name="Grouping.xml" finished-at="2024-08-25T15:56:29 IST" duration-ms="3252">
      <class name="testScript.LoginPage_Test">
        <test-method is-config="true" signature="initialiseBrowser(java.lang.String)[pri:0, instance:testScript.LoginPage_Test@c05fddc]" started-at="2024-08-25T15:56:26 IST" name="initialiseBrowser" finished-at="2024-08-25T15:56:29 IST" duration-ms="3080" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialiseBrowser -->
        <test-method signature="verify_User_is_Able_toLoginUsing_Invalid_UserName_and_Validpassword()[pri:0, instance:testScript.LoginPage_Test@c05fddc]" started-at="2024-08-25T15:56:29 IST" name="verify_User_is_Able_toLoginUsing_Invalid_UserName_and_Validpassword" finished-at="2024-08-25T15:56:29 IST" duration-ms="68" status="FAIL">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[C:\Users\jeffk\git\7RMart-SuperMarket\Automation_Project\src\main\resources\TestData.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: C:\Users\jeffk\git\7RMart-SuperMarket\Automation_Project\src\main\resources\TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at utilities.Excel_Utilities.getStringData(Excel_Utilities.java:21)
at testScript.LoginPage_Test.verify_User_is_Able_toLoginUsing_Invalid_UserName_and_Validpassword(LoginPage_Test.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_User_is_Able_toLoginUsing_Invalid_UserName_and_Validpassword -->
      </class> <!-- testScript.LoginPage_Test -->
    </test> <!-- Grouping.xml -->
  </suite> <!-- Grouping -->
</testng-results>
